[rule.add-constant]
enable = true
description = "Enforce the addition of a constant to the code."

[rule.argument-limit]
enable = true
description = "Enforce a limit on the number of function arguments."

[rule.atomic]
enable = true
description = "Ensure atomic operations are used appropriately."

[rule.bare-return]
enable = true
description = "Enforce using explicit return statements rather than bare returns."

[rule.blank-imports]
enable = true
description = "Enforce avoiding blank imports."

[rule.bool-literal-in-expr]
enable = true
description = "Enforce using boolean literals in expressions."

[rule.call-to-gc]
enable = true
description = "Enforce avoiding direct calls to the garbage collector."

[rule.confusing-naming]
enable = true
description = "Flag variables or identifiers with confusing names."

[rule.confusing-results]
enable = true
description = "Flag the use of confusing return types or values."

[rule.cognitive-complexity]
enable = true
description = "Enforce limits on cognitive complexity in functions."

[rule.constant-logical-expr]
enable = true
description = "Flag complex logical expressions with constants."

[rule.context-as-argument]
enable = true
description = "Flag the use of context as a function argument."

[rule.context-keys-type]
enable = true
description = "Enforce using specific types for context keys."

[rule.cyclomatic]
enable = true
description = "Enforce limits on cyclomatic complexity."

[rule.deep-exit]
enable = true
description = "Flag deep nesting or excessive exits."

[rule.defer]
enable = true
description = "Enforce checking deferred function calls."

[rule.dot-imports]
enable = true
description = "Enforce avoiding dot imports."

[rule.duplicated-imports]
enable = true
description = "Flag duplicated import statements."

[rule.early-return]
enable = true
description = "Enforce avoiding early return statements."

[rule.empty-block]
enable = true
description = "Flag empty blocks of code."

[rule.empty-lines]
enable = true
description = "Enforce avoiding excessive empty lines."

[rule.error-naming]
enable = true
description = "Flag errors with inappropriate names."

[rule.error-return]
enable = true
description = "Flag issues with error return statements."

[rule.error-strings]
enable = true
description = "Flag errors using strings instead of error type."

[rule.errorf]
enable = true
description = "Flag issues with errorf usage."

[rule.flag-parameter]
enable = true
description = "Flag parameters with `flag` package types."

[rule.function-result-limit]
enable = true
description = "Enforce a limit on the number of function results."

[rule.function-length]
enable = true
description = "Enforce limits on function length."

[rule.get-return]
enable = true
description = "Flag issues with using get return statements."

[rule.identical-branches]
enable = true
description = "Flag identical code branches."

[rule.if-return]
enable = true
description = "Enforce avoiding if return statements."

[rule.increment-decrement]
enable = true
description = "Flag issues with increment/decrement operations."

[rule.indent-error-flow]
enable = true
description = "Flag indentation errors in error flows."

[rule.imports-blacklist]
enable = true
description = "Flag import statements that are blacklisted."

[rule.import-shadowing]
enable = true
description = "Flag issues with import shadowing."

[rule.line-length-limit]
enable = true
description = "Enforce a limit on the length of a line."

[rule.max-public-structs]
enable = true
description = "Enforce a limit on the number of public structs in a file."

[rule.modifies-parameter]
enable = true
description = "Flag parameters that modify a value."

[rule.modifies-value-receiver]
enable = true
description = "Flag value receiver methods that modify their receiver."

[rule.nested-structs]
enable = true
description = "Flag nested structs."

[rule.range]
enable = true
description = "Flag issues with using range statements."

[rule.range-val-in-closure]
enable = true
description = "Flag range value used in closures."

[rule.range-val-address]
enable = true
description = "Flag range value address usage."

[rule.receiver-naming]
enable = true
description = "Flag receiver naming issues."

[rule.redefines-builtin-id]
enable = true
description = "Flag redefinition of built-in identifiers."

[rule.string-of-int]
enable = true
description = "Flag issues with converting integers to strings."

[rule.struct-tag]
enable = true
description = "Flag issues with struct tags."

[rule.string-format]
enable = true
description = "Flag issues with string formatting."

[rule.superfluous-else]
enable = true
description = "Flag superfluous else statements."

[rule.time-naming]
enable = true
description = "Flag issues with time package naming."

[rule.var-naming]
enable = true
description = "Flag issues with variable naming."

[rule.var-declaration]
enable = true
description = "Flag issues with variable declaration."

[rule.unconditional-recursion]
enable = true
description = "Flag unconditional recursion."

[rule.unexported-naming]
enable = true
description = "Flag issues with unexported names."

[rule.unexported-return]
enable = true
description = "Flag issues with unexported return statements."

[rule.unhandled-error]
enable = true
description = "Flag unhandled error occurrences."

[rule.unnecessary-stmt]
enable = true
description = "Flag unnecessary statements."

[rule.unreachable-code]
enable = true
description = "Flag unreachable code."

[rule.unused-parameter]
enable = true
description = "Flag unused parameters."

[rule.unused-receiver]
enable = true
description = "Flag unused receivers."

[rule.waitgroup-by-value]
enable = true
description = "Flag usage of sync.WaitGroup by value."