// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Url struct {
	ID             int64     `json:"id"`
	UrlEncoded     string    `json:"url_encoded"`
	UrlOriginal    string    `json:"url_original"`
	ExpirationDate time.Time `json:"expiration_date"`
	CreatedAt      time.Time `json:"created_at"`
}
